/* Drift net over the About modal's account of the software it ships.
 *
 * The libraries section states its own rule, "runtime code in the shipped
 * bundle, not build tooling". A hand-written list kept that rule until it
 * quietly stopped: it credited 14 of the 37 packages that ship, named Vite
 * (which contributes no module) and missed html2canvas and the whole canvg
 * stack, each of which ships as its own chunk exactly the way DOMPurify does,
 * DOMPurify having been credited for that reason. Nothing failed.
 *
 * So the list is generated by scripts/gen-licenses.js and this is the net,
 * built the way tests/aboutCoverage.spec.ts is built: it reads the tree
 * rather than a second copy of the expectations. Two independent things can
 * go wrong and each has its own case.
 *
 * A dependency bump is the everyday one, and the first case catches it with
 * no build: versions and licence texts are read straight out of node_modules.
 * A dependency ADDED to the bundle only shows up against a build, which is
 * the second case; `npm run verify` runs the tests before `vite build`, so a
 * stale or missing dist/ is reported rather than passing silently. */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { collect, shippedPackages } from '../scripts/gen-licenses.js';
import { THIRD_PARTY_LICENSES } from '../src/lib/data/thirdPartyLicenses';
import { THIRD_PARTY_LICENSE_TEXTS } from '../src/lib/data/thirdPartyLicenseTexts';

const root = new URL('..', import.meta.url).pathname;
const dist = join(root, 'dist');
const modules = join(root, 'node_modules');

/** A build is optional here: a fresh clone that has only run `npm test` has
 *  no dist/, and that is not a failure, it is a case this file cannot judge. */
const built = existsSync(join(dist, 'assets')) && existsSync(join(dist, 'sw.js'));

describe('third-party licences', () => {
	it('credits every package at the version installed', () => {
		const wrong: string[] = [];
		for (const entry of THIRD_PARTY_LICENSES) {
			const pkgPath = join(modules, entry.id, 'package.json');
			if (!existsSync(pkgPath)) {
				wrong.push(`${entry.id}: credited but not installed`);
				continue;
			}
			const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as {
				version?: string;
				license?: string;
			};
			if (pkg.version !== entry.version) {
				wrong.push(`${entry.id}: credited ${entry.version}, installed ${String(pkg.version)}`);
			}
			if ((pkg.license ?? '') !== entry.spdx) {
				wrong.push(`${entry.id}: credited ${entry.spdx}, declares ${String(pkg.license)}`);
			}
		}
		expect(
			wrong,
			`run \`npm run build && npm run gen:licenses\`:\n  ${wrong.join('\n  ')}`,
		).toEqual([]);
	});

	it('carries the licence text each package ships, verbatim', () => {
		const wrong: string[] = [];
		for (const entry of THIRD_PARTY_LICENSES) {
			const text = THIRD_PARTY_LICENSE_TEXTS[entry.id];
			// An empty text is worse than no entry: the page would name a
			// licence and show nothing where its notice belongs.
			if (!text) {
				wrong.push(`${entry.id}: no licence text`);
				continue;
			}
			const dir = join(modules, entry.id);
			if (!existsSync(dir)) {
				continue;
			}
			const files = readdirSync(dir)
				.filter((f) => /^(licen[cs]e|copying|notice)/i.test(f))
				.filter((f) => statSync(join(dir, f)).isFile())
				.sort();
			if (!files.length) {
				// The package ships none, so the text came from upstream and
				// entry.files records where. Nothing local to compare it to.
				expect(entry.files.length, `${entry.id}: no licence file and no recorded source`).toBeGreaterThan(0);
				continue;
			}
			if (files.join(',') !== entry.files.join(',')) {
				wrong.push(`${entry.id}: read ${entry.files.join(',')}, ships ${files.join(',')}`);
				continue;
			}
			for (const file of files) {
				const shipped = readFileSync(join(dir, file), 'utf-8').trim();
				if (shipped && !text.includes(shipped.slice(0, 200))) {
					wrong.push(`${entry.id}/${file}: text differs from the installed package`);
				}
			}
		}
		expect(
			wrong,
			`run \`npm run build && npm run gen:licenses\`:\n  ${wrong.join('\n  ')}`,
		).toEqual([]);
	});

	it('has no text for a package it does not credit', () => {
		const credited = new Set(THIRD_PARTY_LICENSES.map((e) => e.id));
		const orphans = Object.keys(THIRD_PARTY_LICENSE_TEXTS).filter((id) => !credited.has(id));
		expect(orphans, `stale licence texts: ${orphans.join(', ')}`).toEqual([]);
	});

	it.runIf(built)('credits everything the build ships, and nothing it does not', () => {
		const shipped = new Set(shippedPackages(dist));
		const credited = new Set(THIRD_PARTY_LICENSES.map((e) => e.id));
		const missing = [...shipped].filter((id) => !credited.has(id)).sort();
		const extra = [...credited].filter((id) => !shipped.has(id)).sort();
		expect(
			{ missing, extra },
			'the bundle and the credit list disagree; run `npm run gen:licenses`',
		).toEqual({ missing: [], extra: [] });
	});

	it.runIf(built)('matches what the generator would write today', () => {
		const fresh = collect(dist, modules);
		expect(fresh.map((e) => `${e.id}@${e.version} ${e.spdx}`)).toEqual(
			THIRD_PARTY_LICENSES.map((e) => `${e.id}@${e.version} ${e.spdx}`),
		);
	});

	it('reports when it could not check the bundle', () => {
		// Not a failure: it names the one case the two cases above skip, so
		// a green run on a tree with no build cannot be mistaken for a
		// complete one.
		expect(
			built || !existsSync(dist),
			'dist/ exists but is incomplete; run `npm run build` before trusting this suite',
		).toBe(true);
	});
});
