/* airspaceGlyphs.ts draws the official SIA activity pictograms at an
 * activity zone's centre, plus the "tres petite zone" rubine cross and the
 * ICAO class chip beside controlled-airspace labels. The pictogram outlines
 * are exact vectors extracted from the SIA's own chart artwork
 * (activityGlyphData.ts, generated by local/glyphs/extract.py; provenance in
 * docs/airspace-symbology.md): each glyph is a list of fill / stroke parts
 * in the chart's paint order, in a unit frame centred on the ink. Knockout
 * parts are the chart's white backing and detail overpaint and draw in the
 * halo colour; everything else takes the caller's colour (SIA.zone rubine).
 * A halo pass under the ink keeps the marks legible on every basemap,
 * exactly like navaidSymbols.ts / airportSymbols.ts. */

import { GLYPH_ART } from './activityGlyphData';
import type { GlyphKind } from './airspaceSymbology';
import { PAPER } from './palette';
import { HALO, haloStroke } from './symbolBase';

/** Glyph half-extent in px; matches the airport / navaid symbol scale. */
export const ACTIVITY_GLYPH_SIZE = 9;

/** Wide silhouettes draw wider than the square box so their height stays
 *  readable (the chart prints the glider long and thin). */
const WIDE_SCALE: Partial<Record<GlyphKind, number>> = {
	glider: 1.4,
	drone: 1.25,
};

/** Extra stroke width (css px) of the white halo around the ink. */
const HALO_PX = 2.2;
/** On-screen floor for the artwork's hairline strokes (css px). */
const MIN_STROKE_PX = 0.8;

type ArtKind = keyof typeof GLYPH_ART;

interface BuiltPart {
	path: Path2D;
	op: 'fill' | 'stroke';
	rule: CanvasFillRule;
	/** Stroke width in glyph units. */
	lw: number;
	knockout: boolean;
}

// Unit-space Path2D objects, built once per kind on first draw. Plain
// module-level cache (this is a .ts module, not reactive state).
const built = new Map<ArtKind, BuiltPart[]>();

function partsFor(kind: ArtKind): BuiltPart[] {
	let parts = built.get(kind);
	if (!parts) {
		parts = GLYPH_ART[kind].parts.map((p) => ({
			path: new Path2D(p.d),
			op: p.op,
			rule: p.eo ? 'evenodd' : 'nonzero',
			lw: p.lw ?? 0,
			knockout: p.knockout ?? false,
		}));
		built.set(kind, parts);
	}
	return parts;
}

function genericPath(x: number, y: number, s: number): Path2D {
	// Six-spoke asterisk for activities without a dedicated chart glyph.
	const p = new Path2D();
	for (let i = 0; i < 3; i++) {
		const a = (Math.PI / 3) * i + Math.PI / 6;
		const dx = Math.cos(a) * s * 0.8;
		const dy = Math.sin(a) * s * 0.8;
		p.moveTo(x - dx, y - dy);
		p.lineTo(x + dx, y + dy);
	}
	return p;
}

/** Drawn half-extent of a glyph in css px (the unit frame times the kind's
 *  display scale); the deco layer offsets the designator label below it. */
export function glyphHalf(kind: GlyphKind): { w: number; h: number } {
	if (kind === 'generic') {
		return { w: ACTIVITY_GLYPH_SIZE * 0.8, h: ACTIVITY_GLYPH_SIZE * 0.8 };
	}
	const k = ACTIVITY_GLYPH_SIZE * (WIDE_SCALE[kind] ?? 1);
	const art = GLYPH_ART[kind];
	return { w: k * art.halfW, h: k * art.halfH };
}

/** Draw an activity glyph centred at (x, y); `emphasized` enlarges the mark
 *  for the highlighted zone. */
export function drawActivityGlyph(
	ctx: CanvasRenderingContext2D,
	kind: GlyphKind,
	x: number,
	y: number,
	color: string,
	emphasized = false,
): void {
	if (kind === 'generic') {
		const s = ACTIVITY_GLYPH_SIZE * (emphasized ? 1.18 : 1);
		haloStroke(ctx, genericPath(x, y, s), color, emphasized ? 2.2 : 1.4);
		return;
	}
	const parts = partsFor(kind);
	const k =
		ACTIVITY_GLYPH_SIZE * (WIDE_SCALE[kind] ?? 1) * (emphasized ? 1.18 : 1);
	ctx.save();
	ctx.translate(x, y);
	ctx.scale(k, k);
	ctx.lineJoin = 'round';
	ctx.lineCap = 'round';
	// Halo under the ink: stroke every ink part's outline in the halo colour
	// (knockouts sit inside the silhouette, the artwork covers them next).
	ctx.strokeStyle = HALO;
	for (const p of parts) {
		if (p.knockout) continue;
		ctx.lineWidth = p.lw + HALO_PX / k;
		ctx.stroke(p.path);
	}
	// The artwork itself, in the chart's paint order.
	const minLw = MIN_STROKE_PX / k;
	for (const p of parts) {
		if (p.op === 'fill') {
			ctx.fillStyle = p.knockout ? HALO : color;
			ctx.fill(p.path, p.rule);
		} else {
			ctx.strokeStyle = p.knockout ? HALO : color;
			ctx.lineWidth = Math.max(p.lw, minLw);
			ctx.stroke(p.path);
		}
	}
	ctx.restore();
}

/** The GEN 2.3 "tres petite zone" mark: a bold rubine cross replacing the
 *  band / glyph of a zone too small on screen for either to read. */
export function drawTinyCross(
	ctx: CanvasRenderingContext2D,
	x: number,
	y: number,
	color: string,
): void {
	// Legende2026 proportions: 14.5 px strokes on a 139 px extent (0.104).
	const arm = 6;
	const p = new Path2D();
	p.moveTo(x - arm, y);
	p.lineTo(x + arm, y);
	p.moveTo(x, y - arm);
	p.lineTo(x, y + arm);
	haloStroke(ctx, p, color, 1.3);
}

/** Side length of the class chip box drawn by drawClassChip. */
export const CHIP_SIZE = 13;

/** Draw the ICAO class chip with its top-left corner at (x, y): a solid box
 *  with a white letter when the class holds H24, the outlined GEN 2.3 form
 *  otherwise. Restores the caller's font. */
export function drawClassChip(
	ctx: CanvasRenderingContext2D,
	x: number,
	y: number,
	letter: string,
	solid: boolean,
	color: string,
): void {
	ctx.save();
	if (solid) {
		ctx.fillStyle = color;
		ctx.fillRect(x, y, CHIP_SIZE, CHIP_SIZE);
	} else {
		ctx.fillStyle = HALO;
		ctx.fillRect(x, y, CHIP_SIZE, CHIP_SIZE);
		ctx.strokeStyle = color;
		ctx.lineWidth = 1.3;
		ctx.strokeRect(x + 0.5, y + 0.5, CHIP_SIZE - 1, CHIP_SIZE - 1);
	}
	ctx.fillStyle = solid ? PAPER : color;
	ctx.font = 'bold 9px system-ui, sans-serif'; // i18n-ignore: CSS font shorthand, not display text
	ctx.textAlign = 'center';
	ctx.textBaseline = 'middle';
	ctx.fillText(letter, x + CHIP_SIZE / 2, y + CHIP_SIZE / 2 + 0.5);
	ctx.restore();
}
