package main

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writePGM builds a GeographicLib-shaped geoid PGM whose undulation is a known
// function of position, so the subsample can be checked against it exactly.
func writePGM(t *testing.T, width, height int, offset, scale float64, n func(row, col int) float64) string {
	t.Helper()
	var b bytes.Buffer
	b.WriteString("P5\n")
	b.WriteString("# Geoid file in PGM format for the GeographicLib::Geoid class\n")
	b.WriteString("# Description WGS84 EGM96, test grid\n")
	fmt.Fprintf(&b, "# Offset %g\n", offset)
	fmt.Fprintf(&b, "# Scale %g\n", scale)
	b.WriteString("# Origin 90N 0E\n")
	fmt.Fprintf(&b, "%d %d\n65535\n", width, height)
	raw := make([]byte, 2)
	for row := 0; row < height; row++ {
		for col := 0; col < width; col++ {
			binary.BigEndian.PutUint16(raw, uint16((n(row, col)-offset)/scale))
			b.Write(raw)
		}
	}
	path := filepath.Join(t.TempDir(), "geoid.pgm")
	if err := os.WriteFile(path, b.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestReadPGM(t *testing.T) {
	// A 1-degree source (360x181) so every emitted node maps to one sample.
	// Values stay inside the header's encodable range (offset + scale*65535).
	want := func(row, col int) float64 { return float64(row)/4 - float64(col)/40 }
	path := writePGM(t, 360, 181, -108, 0.003, want)

	g, err := readPGM(path)
	if err != nil {
		t.Fatalf("readPGM: %v", err)
	}
	if g.width != 360 || g.height != 181 {
		t.Fatalf("dimensions = %dx%d, want 360x181", g.width, g.height)
	}
	if g.description != "WGS84 EGM96, test grid" {
		t.Errorf("description = %q", g.description)
	}
	for _, c := range []struct{ row, col int }{{0, 0}, {90, 180}, {180, 359}} {
		if got := g.at(c.row, c.col); got-want(c.row, c.col) > 0.01 || want(c.row, c.col)-got > 0.01 {
			t.Errorf("at(%d,%d) = %g, want %g", c.row, c.col, got, want(c.row, c.col))
		}
	}
	// Longitude wraps, so the column past the last is the first again.
	if g.at(0, 360) != g.at(0, 0) {
		t.Errorf("at(0,360) = %g, want the wrap to at(0,0) = %g", g.at(0, 360), g.at(0, 0))
	}
}

func TestReadPGMRejectsNonGeoid(t *testing.T) {
	path := filepath.Join(t.TempDir(), "bad.pgm")
	if err := os.WriteFile(path, []byte("P2\n2 2\n255\n1 2 3 4\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := readPGM(path); err == nil {
		t.Fatal("expected an error on a non-binary PGM")
	}
}

func TestSubsample(t *testing.T) {
	// A source at four samples per degree, the real 15-minute spacing, so the
	// subsample has to pick nodes rather than neighbours.
	src := func(row, col int) float64 {
		lat := 90 - float64(row)/4
		lon := float64(col) / 4
		return lat/10 - lon/20
	}
	path := writePGM(t, 1440, 721, -108, 0.003, src)
	g, err := readPGM(path)
	if err != nil {
		t.Fatalf("readPGM: %v", err)
	}
	grid := subsample(g)
	if len(grid) != rows*cols {
		t.Fatalf("grid length = %d, want %d", len(grid), rows*cols)
	}
	// Spot-check nodes against the source, allowing only the metre rounding.
	for _, c := range []struct{ lat, lon float64 }{{90, -180}, {48, 2}, {-45, 90}, {-90, 180}} {
		i := int(90 - c.lat)
		j := int(c.lon + 180)
		row := int((90 - c.lat) * 4)
		col := int(((c.lon + 360) * 4))
		if col >= 1440 {
			col -= 1440
		}
		got := float64(grid[i*cols+j])
		if diff := got - src(row, col); diff > 0.5 || diff < -0.5 {
			t.Errorf("node (%g,%g) = %g, want %g", c.lat, c.lon, got, src(row, col))
		}
	}
	// The antimeridian column is the repeat that spares the reader a wrap.
	for i := 0; i < rows; i++ {
		if grid[i*cols] != grid[i*cols+cols-1] {
			t.Fatalf("row %d: 180W = %d but 180E = %d", i, grid[i*cols], grid[i*cols+cols-1])
		}
	}
}

func TestRenderRoundTrips(t *testing.T) {
	grid := make([]int8, rows*cols)
	for i := range grid {
		grid[i] = int8(i%200 - 100)
	}
	out := string(render(grid, "test"))
	if !strings.Contains(out, "GENERATED by cmd/geoid") {
		t.Error("missing the generated-file header")
	}
	if !strings.Contains(out, "export const GEOID_ROWS = 181;") {
		t.Error("missing the lattice dimensions")
	}
	start := strings.Index(out, "GEOID_B64 = `")
	if start < 0 {
		t.Fatal("missing the base64 payload")
	}
	payload := out[start+len("GEOID_B64 = `"):]
	payload = payload[:strings.Index(payload, "`")]
	raw, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(payload, "\n", ""))
	if err != nil {
		t.Fatalf("payload does not decode: %v", err)
	}
	if len(raw) != len(grid) {
		t.Fatalf("decoded %d bytes, want %d", len(raw), len(grid))
	}
	for i := range grid {
		if int8(raw[i]) != grid[i] {
			t.Fatalf("byte %d = %d, want %d", i, int8(raw[i]), grid[i])
		}
	}
}
