/* EGM96 geoid undulation: the height of mean sea level above the WGS84
 * ellipsoid at a position, which is the term that turns an ellipsoidal GNSS
 * height into one comparable with a published altitude. Around metropolitan
 * France it runs +44 to +51 m, so it is the difference between an altitude
 * that agrees with the chart and one about 150 ft above it.
 *
 * The lattice is generated by cmd/geoid and embedded (nav/geoidData.ts)
 * rather than fetched: the resolver has to answer synchronously at the first
 * fix, before any dataset could have loaded. Decoded once, on first use.
 *
 * Pure, no Svelte, no I/O; tests/navGeoid.spec.ts. */

import { GEOID_B64, GEOID_COLS, GEOID_ROWS, GEOID_STEP_DEG } from './geoidData';

/** Metres in one foot. */
const M_PER_FT = 0.3048;

let grid: Int8Array | null = null;

function lattice(): Int8Array {
	if (grid === null) {
		const raw = atob(GEOID_B64.replace(/\s+/g, ''));
		const out = new Int8Array(raw.length);
		for (let i = 0; i < raw.length; i++) {
			// charCodeAt gives 0..255; Int8Array reinterprets the sign.
			out[i] = raw.charCodeAt(i);
		}
		grid = out;
	}
	return grid;
}

/** Geoid undulation N (metres) at a position: add it to an orthometric (MSL)
 *  height to get an ellipsoidal one, subtract it to go the other way.
 *  Bilinear over the whole-degree lattice; latitude is clamped to the poles
 *  and longitude wrapped, so every input answers. */
export function geoidHeightM(lat: number, lon: number): number {
	const g = lattice();
	const step = GEOID_STEP_DEG;
	const clampedLat = lat > 90 ? 90 : lat < -90 ? -90 : lat;
	// Wrap into [-180, 180]; the lattice repeats the antimeridian column, so
	// the cell to the east of +179 is present and no wrap branch is needed.
	let wrappedLon = ((lon + 180) % 360 + 360) % 360 - 180;
	if (!Number.isFinite(wrappedLon)) {
		wrappedLon = 0;
	}
	const y = (90 - clampedLat) / step;
	const x = (wrappedLon + 180) / step;
	const i0 = Math.min(GEOID_ROWS - 2, Math.max(0, Math.floor(y)));
	const j0 = Math.min(GEOID_COLS - 2, Math.max(0, Math.floor(x)));
	const fy = y - i0;
	const fx = x - j0;
	const a = g[i0 * GEOID_COLS + j0];
	const b = g[i0 * GEOID_COLS + j0 + 1];
	const c = g[(i0 + 1) * GEOID_COLS + j0];
	const d = g[(i0 + 1) * GEOID_COLS + j0 + 1];
	return (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy;
}

/** The same undulation in feet, the unit every altitude in the app is in. */
export function geoidHeightFt(lat: number, lon: number): number {
	return geoidHeightM(lat, lon) / M_PER_FT;
}
