/* i18n-lint: the localisation guard (contract: docs/i18n.md).
 *
 * Scans the Svelte markup and the user-visible TS modules for hardcoded
 * strings that belong in the src/lib/i18n catalogs, enforces the catalog
 * authoring rules, and compares finding counts against a shrink-only
 * baseline (scripts/i18n-baseline.json):
 *
 *   - a file may never gain findings over its baseline;
 *   - a file absent from the baseline must be clean (new code is born
 *     translated);
 *   - `node scripts/i18n-lint.js --update` records progress and refuses to
 *     raise any count (translate instead of baselining).
 *
 * Rule findings (never baselined, always fatal):
 *   - `t` captured in a top-level / module-scope const or a $props()
 *     fallback, including aliasing t or destructuring a domain off it
 *     (freezes the language; use $derived or translate in the template);
 *   - a {#key} block keyed on the locale (remounts the subtree; t.* reads
 *     re-render on their own);
 *   - a canvas module (src/lib/map/) importing the catalogs, statically,
 *     via a re-export or a dynamic import() (canvas only redraws on
 *     pan/zoom, so baked translated text goes stale);
 *   - French typography in src/lib/i18n/fr (ASCII space before : ; ! ?,
 *     guillemets) and em-dashes in any catalog (repo rule), interpolated
 *     template pieces included.
 *   - an edited src/lib/i18n/en/<domain>.ts without its fr twin in the same
 *     working diff (semantic drift; escape hatch: I18N_ALLOW_DRIFT=1).
 *
 * Suppressions: a line containing `i18n-ignore` suppresses findings on the
 * same and the next line; `i18n-ignore-start` / `i18n-ignore-end` suppress a
 * block (for canonical English kept in place by design, with the reason on
 * the marker line).
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'svelte/compiler';
import ts from 'typescript';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const BASELINE_PATH = join(ROOT, 'scripts/i18n-baseline.json');
const UPDATE = process.argv.includes('--update');

const CATEGORIES = ['text', 'attr', 'expr', 'script'];

/** Attributes whose literal text the user reads. */
const TRANSLATABLE_ATTRS = new Set([
	'alt',
	'aria-description',
	'aria-label',
	'label',
	'placeholder',
	'title',
]);

/** Files that keep English on purpose; the reason is part of the contract.
 *  Mixed files use i18n-ignore-start/end blocks instead. */
const EXCLUDED_TS = new Set([
	'src/main.ts', // boot-failure throw, developer-facing
	'src/lib/notam/qcode.ts', // canonical EN decode tables; FR mirror in $lib/i18n
	'src/lib/aircraft/schema.ts', // validation errors stay EN (deferred by decision)
	'src/lib/aircraft/edit.ts', // validation-error plumbing, same decision
	'src/lib/data/license.ts', // MIT licence text, legal instrument
	'src/lib/vertical/limits.ts', // SIA vocabulary, locale-invariant by decision
	'src/lib/nav/gpx.ts', // GPX wire format: XML tags + parse diagnostic (never shown)
	'src/lib/nav/geoidData.ts', // generated by cmd/geoid: one base64 numeric lattice
	// Generated by scripts/gen-licenses.js from each package's own files:
	// legal instruments in the language their authors wrote them, rendered
	// lang="en" like the app's own licence. Translating one would change it.
	'src/lib/data/thirdPartyLicenseTexts.ts',
	'src/lib/data/thirdPartyLicenses.ts', // the same, minus the texts: package and licence names
]);

/** Unit tokens allowed as bare markup text between value expressions. */
const UNIT_TOKENS = new Set([
	'ft',
	'ft/min',
	'h',
	'hpa',
	'kg',
	'khz',
	'km',
	'km/h',
	'kt',
	'kts',
	'l',
	'm',
	'mhz',
	'min',
	'nm',
	's',
	'utc',
]);

const LOWER_RUN = /\p{Ll}{2}/u;
// \s already covers NBSP and the narrow no-break space.
const SENTENCE = /\p{Ll}{2,}\s+\p{L}/u;

/** @typedef {{file: string, line: number, category: string, snippet: string}} Finding */
/** @type {Finding[]} */
const findings = [];
/** @type {Finding[]} */
const ruleErrors = [];

function record(list, file, line, category, snippet) {
	list.push({
		file,
		line,
		category,
		snippet: snippet.replace(/\s+/g, ' ').trim().slice(0, 70),
	});
}

/* ------------------------------ suppression ------------------------------ */

/** Line-based suppression set for one source: `i18n-ignore` covers its own
 *  and the next line, start/end markers cover the block between them. */
function suppressedLines(source) {
	const lines = source.split('\n');
	const set = new Set();
	let inBlock = false;
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (line.includes('i18n-ignore-start')) {
			inBlock = true;
		}
		if (inBlock) {
			set.add(i + 1);
		}
		if (line.includes('i18n-ignore-end')) {
			inBlock = false;
		}
		if (/i18n-ignore(?!-start|-end)/.test(line)) {
			set.add(i + 1);
			set.add(i + 2);
		}
	}
	return set;
}

function lineIndex(source) {
	const starts = [0];
	for (let i = 0; i < source.length; i++) {
		if (source[i] === '\n') {
			starts.push(i + 1);
		}
	}
	return (offset) => {
		let lo = 0;
		let hi = starts.length - 1;
		while (lo < hi) {
			const mid = (lo + hi + 1) >> 1;
			if (starts[mid] <= offset) {
				lo = mid;
			} else {
				hi = mid - 1;
			}
		}
		return lo + 1;
	};
}

/* ------------------------------- heuristics ------------------------------ */

/** Markup / attribute text is translatable when any whitespace token keeps a
 *  two-lowercase-letter run after stripping punctuation, unless the token is
 *  a unit or an all-caps code (NOTAM, VFR, ILS, designators). */
function textIsTranslatable(text) {
	for (const raw of text.split(/\s+/)) {
		const token = raw.replace(/^[^\p{L}]+|[^\p{L}]+$/gu, '');
		if (token === '' || UNIT_TOKENS.has(token.toLowerCase())) {
			continue;
		}
		if (/^[\p{Lu}0-9/.-]+$/u.test(token)) {
			continue;
		}
		if (LOWER_RUN.test(token)) {
			return true;
		}
	}
	return false;
}

function sentenceLike(text) {
	return SENTENCE.test(text);
}

/* --------------------------- ESTree walk (svelte) ------------------------ */

/** True when an expression reads the locale (the `i18n` state object or a
 *  `locale` binding): the {#key} remount ban's predicate. */
function referencesLocale(node) {
	if (node === null || typeof node !== 'object') {
		return false;
	}
	if (Array.isArray(node)) {
		return node.some(referencesLocale);
	}
	if (node.type === 'Identifier' && (node.name === 'locale' || node.name === 'i18n')) {
		return true;
	}
	for (const key of Object.keys(node)) {
		if (key === 'parent' || key === 'metadata' || key === 'loc') {
			continue;
		}
		const value = node[key];
		if (value !== null && typeof value === 'object' && referencesLocale(value)) {
			return true;
		}
	}
	return false;
}

/** Walks the modern Svelte AST (fragment or embedded ESTree alike). ctx is
 *  'markup' | 'attr' | 'expr' | 'skip' and only Attribute nodes change it. */
function walkSvelte(node, ctx, out) {
	if (node === null || typeof node !== 'object') {
		return;
	}
	if (Array.isArray(node)) {
		for (const item of node) {
			walkSvelte(item, ctx, out);
		}
		return;
	}
	switch (node.type) {
		case 'Comment':
			return;
		case 'Text': {
			if (ctx === 'skip') {
				return;
			}
			// Fragment text and attribute text chunks share the node type; the
			// category follows the context.
			if (typeof node.data === 'string' && textIsTranslatable(node.data)) {
				out(node.start, ctx === 'attr' ? 'attr' : 'text', node.data);
			}
			return;
		}
		case 'Attribute': {
			const name = String(node.name);
			let next = 'skip';
			if (TRANSLATABLE_ATTRS.has(name)) {
				next = 'attr';
			} else if (/^on[a-z]/.test(name)) {
				// Inline handlers can assign user-visible strings.
				next = 'expr';
			}
			if (next !== 'skip') {
				walkSvelte(node.value, next, out);
			}
			return;
		}
		case 'SpreadAttribute':
		case 'BindDirective':
		case 'ClassDirective':
		case 'StyleDirective':
		case 'UseDirective':
		case 'TransitionDirective':
		case 'AnimateDirective':
		case 'OnDirective':
		case 'LetDirective':
			return;
		case 'Literal': {
			if (ctx !== 'skip' && typeof node.value === 'string' && sentenceLike(node.value)) {
				out(node.start, ctx === 'markup' ? 'expr' : ctx, node.value);
			}
			return;
		}
		case 'TemplateElement': {
			const cooked = node.value && node.value.cooked;
			if (ctx !== 'skip' && typeof cooked === 'string' && sentenceLike(cooked)) {
				out(node.start, ctx === 'markup' ? 'expr' : ctx, cooked);
			}
			return;
		}
		case 'Property': {
			// Skip non-computed keys: they are identifiers, not display text.
			if (!node.computed) {
				walkSvelte(node.value, ctx, out);
				return;
			}
			break;
		}
		case 'ImportDeclaration':
		case 'ExportAllDeclaration':
			return;
		case 'KeyBlock': {
			// {#key locale} destroys and remounts the subtree on every
			// language switch; t.* reads re-render on their own.
			if (referencesLocale(node.expression)) {
				out(node.start, 'rule', '{#key} keyed on the locale (t.* re-renders on its own; drop the remount)');
			}
			break;
		}
		case 'CallExpression': {
			const callee = node.callee;
			if (
				callee &&
				callee.type === 'MemberExpression' &&
				callee.object &&
				callee.object.type === 'Identifier' &&
				callee.object.name === 'console'
			) {
				return;
			}
			break;
		}
		default:
			break;
	}
	for (const key of Object.keys(node)) {
		if (key === 'parent' || key === 'metadata' || key === 'loc') {
			continue;
		}
		const value = node[key];
		if (value !== null && typeof value === 'object') {
			walkSvelte(value, ctx, out);
		}
	}
}

/** The t-capture rule over an ESTree Program: a top-level const initializer
 *  reading `t.<domain>` outside a function body or a $derived(...) freezes
 *  the language at init. */
function checkTCaptureEstree(program, out) {
	const importsT = program.body.some(
		(n) =>
			n.type === 'ImportDeclaration' &&
			String(n.source.value).includes('state/i18n.svelte') &&
			n.specifiers.some(
				(s) => s.type === 'ImportSpecifier' && s.imported && s.imported.name === 't',
			),
	);
	if (!importsT) {
		return;
	}
	const findT = (node) => {
		if (node === null || typeof node !== 'object') {
			return null;
		}
		if (Array.isArray(node)) {
			for (const item of node) {
				const hit = findT(item);
				if (hit) {
					return hit;
				}
			}
			return null;
		}
		if (
			node.type === 'ArrowFunctionExpression' ||
			node.type === 'FunctionExpression' ||
			node.type === 'FunctionDeclaration'
		) {
			return null;
		}
		if (
			node.type === 'CallExpression' &&
			((node.callee.type === 'Identifier' && node.callee.name === '$derived') ||
				(node.callee.type === 'MemberExpression' &&
					node.callee.object.type === 'Identifier' &&
					node.callee.object.name === '$derived'))
		) {
			return null;
		}
		// A bare reference to t (aliasing it, destructuring a domain off it,
		// passing it into a stored closure) captures the accessor just as a
		// t.* read does.
		if (node.type === 'Identifier') {
			return node.name === 't' ? node : null;
		}
		if (node.type === 'MemberExpression') {
			// Only the object position reads a value; a non-computed `.t`
			// property name is a label, not the accessor.
			return findT(node.object) ?? (node.computed ? findT(node.property) : null);
		}
		if (node.type === 'Property' && !node.computed) {
			// Non-computed keys are names; shorthand `{ t }` still hits
			// through its value node.
			return findT(node.value);
		}
		for (const key of Object.keys(node)) {
			if (key === 'parent' || key === 'loc') {
				continue;
			}
			const value = node[key];
			if (value !== null && typeof value === 'object') {
				const hit = findT(value);
				if (hit) {
					return hit;
				}
			}
		}
		return null;
	};
	for (const stmt of program.body) {
		// `export const x = t...` wraps the declaration in an
		// ExportNamedDeclaration; unwrap it so the rule still applies.
		const target =
			stmt.type === 'ExportNamedDeclaration' && stmt.declaration ? stmt.declaration : stmt;
		if (target.type !== 'VariableDeclaration') {
			continue;
		}
		for (const decl of target.declarations) {
			// A t.* fallback in a destructuring default ($props() included)
			// evaluates once at init, so the pattern side freezes too.
			const idHit = findT(decl.id);
			if (idHit) {
				const isProps =
					decl.init &&
					decl.init.type === 'CallExpression' &&
					decl.init.callee.type === 'Identifier' &&
					decl.init.callee.name === '$props';
				out(
					idHit.start,
					'rule',
					isProps
						? 't.* in a $props() fallback (evaluated once at mount; use $derived or default in the template)'
						: 't.* captured in a top-level const (use $derived or translate in the template)',
				);
				continue;
			}
			const hit = decl.init ? findT(decl.init) : null;
			if (hit) {
				out(hit.start, 'rule', 't.* captured in a top-level const (use $derived or translate in the template)');
			}
		}
	}
}

/* ------------------------------ TS module walk --------------------------- */

function scanTsSource(file, source) {
	const suppressed = suppressedLines(source);
	const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
	const lineOf = (node) => sf.getLineAndCharacterOfPosition(node.getStart(sf)).line + 1;

	const push = (node, category, snippet) => {
		const line = lineOf(node);
		if (!suppressed.has(line)) {
			record(findings, file, line, category, snippet);
		}
	};

	const visit = (node) => {
		if (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) {
			return;
		}
		if (
			ts.isCallExpression(node) &&
			ts.isPropertyAccessExpression(node.expression) &&
			ts.isIdentifier(node.expression.expression) &&
			node.expression.expression.text === 'console'
		) {
			return;
		}
		if (ts.isPropertyAssignment(node)) {
			visit(node.initializer);
			return;
		}
		if (ts.isEnumMember(node)) {
			if (node.initializer) {
				visit(node.initializer);
			}
			return;
		}
		if (ts.isLiteralTypeNode(node)) {
			return;
		}
		if (
			ts.isElementAccessExpression(node) &&
			ts.isStringLiteral(node.argumentExpression)
		) {
			visit(node.expression);
			return;
		}
		if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
			if (sentenceLike(node.text)) {
				push(node, 'script', node.text);
			}
			return;
		}
		if (ts.isTemplateExpression(node)) {
			if (sentenceLike(node.head.text)) {
				push(node.head, 'script', node.head.text);
			}
			for (const span of node.templateSpans) {
				visit(span.expression);
				if (sentenceLike(span.literal.text)) {
					push(span.literal, 'script', span.literal.text);
				}
			}
			return;
		}
		ts.forEachChild(node, visit);
	};
	visit(sf);

	// The t-capture rule for TS modules importing the accessor (.svelte.ts
	// state modules and plain .ts alike): a module-scope const holding
	// translated text freezes the language.
	if (/from '\$lib\/state\/i18n\.svelte'|from '\.\/i18n\.svelte'/.test(source)) {
		const findT = (node) => {
			if (ts.isFunctionLike(node)) {
				return null;
			}
			if (
				ts.isCallExpression(node) &&
				ts.isIdentifier(node.expression) &&
				node.expression.text === '$derived'
			) {
				return null;
			}
			// A bare reference to t (aliasing it, destructuring a domain off
			// it) captures the accessor just as a t.* read does.
			if (ts.isIdentifier(node)) {
				return node.text === 't' ? node : null;
			}
			if (ts.isPropertyAccessExpression(node)) {
				// Only the object position reads a value; the `.name` side is
				// a label, not the accessor.
				return findT(node.expression);
			}
			if (ts.isPropertyAssignment(node)) {
				// Object keys are names; shorthand `{ t }` still hits through
				// its own node kind.
				return findT(node.initializer);
			}
			return ts.forEachChild(node, findT) ?? null;
		};
		for (const stmt of sf.statements) {
			if (!ts.isVariableStatement(stmt)) {
				continue;
			}
			for (const decl of stmt.declarationList.declarations) {
				// decl.name covers t.* defaults inside destructuring patterns.
				const hit = (decl.initializer ? findT(decl.initializer) : null) ?? findT(decl.name);
				if (hit && !suppressed.has(lineOf(hit))) {
					record(
						ruleErrors,
						file,
						lineOf(hit),
						'rule',
						't.* captured in a module-scope const (read it inside a $derived or function instead)',
					);
				}
			}
		}
	}

	// Canvas import ban: src/lib/map modules must not read the catalogs,
	// whether by static import, export-from re-export, or dynamic import().
	if (file.startsWith('src/lib/map/')) {
		const bansCatalog = (spec) => /(^|\/)i18n(\/|$|\.)/.test(spec);
		const ban = (node, spec) => {
			record(
				ruleErrors,
				file,
				lineOf(node),
				'rule',
				`canvas module imports ${spec} (canvas text goes stale on locale switch; keep it invariant)`,
			);
		};
		for (const stmt of sf.statements) {
			if (
				(ts.isImportDeclaration(stmt) || ts.isExportDeclaration(stmt)) &&
				stmt.moduleSpecifier &&
				ts.isStringLiteral(stmt.moduleSpecifier) &&
				bansCatalog(stmt.moduleSpecifier.text)
			) {
				ban(stmt, stmt.moduleSpecifier.text);
			}
		}
		const findDynamicImport = (node) => {
			if (
				ts.isCallExpression(node) &&
				node.expression.kind === ts.SyntaxKind.ImportKeyword &&
				node.arguments.length > 0 &&
				ts.isStringLiteralLike(node.arguments[0]) &&
				bansCatalog(node.arguments[0].text)
			) {
				ban(node, node.arguments[0].text);
			}
			ts.forEachChild(node, findDynamicImport);
		};
		findDynamicImport(sf);
	}
}

/* ---------------------------- catalog typography -------------------------- */

function scanCatalogTypography(file, source) {
	const suppressed = suppressedLines(source);
	const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
	const isFr = file.includes('/i18n/fr/');
	const check = (text, node) => {
		const line = sf.getLineAndCharacterOfPosition(node.getStart(sf)).line + 1;
		if (suppressed.has(line)) {
			return;
		}
		if (text.includes('\u2014')) {
			record(ruleErrors, file, line, 'rule', 'em-dash in a catalog string (repo rule: use ; : , or split)');
		}
		if (isFr) {
			if (/ [:;!?]/.test(text)) {
				record(ruleErrors, file, line, 'rule', 'ASCII space before high punctuation in French (use \\u202f)');
			}
			if (/[«»]/.test(text)) {
				record(ruleErrors, file, line, 'rule', 'guillemets in a catalog string (plain quotes, docs/i18n.md)');
			}
		}
	};
	const visit = (node) => {
		if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
			check(node.text, node);
		} else if (ts.isTemplateExpression(node)) {
			// Interpolated templates are the dominant catalog message form:
			// the head and every span literal carry display text too.
			check(node.head.text, node.head);
			for (const span of node.templateSpans) {
				check(span.literal.text, span.literal);
			}
		}
		ts.forEachChild(node, visit);
	};
	visit(sf);
}

/* --------------------------------- drift --------------------------------- */

function checkDrift() {
	if (process.env.I18N_ALLOW_DRIFT) {
		return;
	}
	let out;
	try {
		out = execFileSync('git', ['diff', '--name-only', 'HEAD', '--', 'src/lib/i18n'], {
			cwd: ROOT,
			encoding: 'utf8',
		});
	} catch {
		return; // not a repo / no HEAD; the check is best-effort
	}
	const changed = new Set(out.split('\n').filter(Boolean));
	for (const path of changed) {
		const m = path.match(/^src\/lib\/i18n\/en\/(.+\.ts)$/);
		if (m && !changed.has(`src/lib/i18n/fr/${m[1]}`)) {
			record(
				ruleErrors,
				path,
				1,
				'rule',
				`edited without its French twin src/lib/i18n/fr/${m[1]} (I18N_ALLOW_DRIFT=1 to override)`,
			);
		}
	}
}

/* --------------------------------- driver -------------------------------- */

function listFiles(dir, out) {
	for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
		const rel = `${dir}/${entry.name}`;
		if (entry.isDirectory()) {
			listFiles(rel, out);
		} else {
			out.push(rel);
		}
	}
	return out;
}

function scan() {
	const files = listFiles('src', []);

	for (const file of files) {
		const source = readFileSync(join(ROOT, file), 'utf8');

		if (file.startsWith('src/lib/i18n/')) {
			if (file.endsWith('.ts')) {
				scanCatalogTypography(file, source);
			}
			continue;
		}

		if (file.endsWith('.svelte')) {
			const suppressed = suppressedLines(source);
			const lineOf = lineIndex(source);
			const out = (offset, category, snippet) => {
				const line = lineOf(offset);
				if (suppressed.has(line)) {
					return;
				}
				if (category === 'rule') {
					record(ruleErrors, file, line, 'rule', snippet);
				} else {
					record(findings, file, line, category, snippet);
				}
			};
			let ast;
			try {
				ast = parse(source, { filename: file, modern: true });
			} catch (err) {
				record(ruleErrors, file, 1, 'rule', `svelte parse failed: ${err.message}`);
				continue;
			}
			walkSvelte(ast.fragment, 'markup', out);
			for (const script of [ast.instance, ast.module]) {
				if (script) {
					walkSvelte(script.content, 'script', out);
					checkTCaptureEstree(script.content, out);
				}
			}
			continue;
		}

		if (
			(file.endsWith('.ts') && file.startsWith('src/lib/')) ||
			file === 'src/main.ts'
		) {
			if (file.endsWith('.d.ts') || EXCLUDED_TS.has(file)) {
				continue;
			}
			scanTsSource(file, source);
		}
	}

	checkDrift();
}

/* -------------------------------- baseline ------------------------------- */

function countsByFile() {
	const map = new Map();
	for (const f of findings) {
		let counts = map.get(f.file);
		if (!counts) {
			counts = {};
			map.set(f.file, counts);
		}
		counts[f.category] = (counts[f.category] ?? 0) + 1;
	}
	return map;
}

function loadBaseline() {
	if (!existsSync(BASELINE_PATH)) {
		return null;
	}
	return JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
}

function main() {
	scan();

	const counts = countsByFile();
	const baseline = loadBaseline();
	const total = findings.length;

	if (ruleErrors.length > 0) {
		console.error(`i18n-lint: ${ruleErrors.length} rule violation(s):`);
		for (const e of ruleErrors.slice(0, 40)) {
			console.error(`  ${e.file}:${e.line}  ${e.snippet}`);
		}
		process.exitCode = 1;
	}

	if (UPDATE) {
		const next = {};
		let raised = false;
		for (const [file, cats] of [...counts.entries()].sort()) {
			next[file] = cats;
			if (baseline) {
				const old = baseline[file] ?? {};
				for (const cat of CATEGORIES) {
					if ((cats[cat] ?? 0) > (old[cat] ?? 0)) {
						console.error(
							`i18n-lint: ${file} ${cat} rose ${old[cat] ?? 0} -> ${cats[cat] ?? 0}; translate instead of baselining`,
						);
						raised = true;
					}
				}
			}
		}
		if (raised) {
			process.exitCode = 1;
			return;
		}
		writeFileSync(BASELINE_PATH, JSON.stringify(next, null, '\t') + '\n');
		console.log(`i18n-lint: baseline updated (${total} findings in ${counts.size} files)`);
		return;
	}

	if (!baseline) {
		console.error('i18n-lint: no baseline; run `node scripts/i18n-lint.js --update` to bootstrap');
		process.exitCode = 1;
		return;
	}

	let violations = 0;
	let shrunk = 0;
	for (const [file, cats] of counts.entries()) {
		const old = baseline[file];
		for (const cat of CATEGORIES) {
			const cur = cats[cat] ?? 0;
			const base = old ? (old[cat] ?? 0) : 0;
			if (cur > base) {
				violations++;
				const label = old ? `over baseline (${base})` : 'new file must be born translated';
				console.error(`i18n-lint: ${file}: ${cur} ${cat} finding(s) ${label}:`);
				for (const f of findings.filter((x) => x.file === file && x.category === cat).slice(0, 8)) {
					console.error(`    :${f.line}  ${f.snippet}`);
				}
			} else if (cur < base) {
				shrunk++;
			}
		}
	}
	for (const file of Object.keys(baseline)) {
		if (!counts.has(file)) {
			shrunk++;
		}
	}

	if (violations > 0) {
		console.error(`i18n-lint: ${violations} file/category count(s) above baseline`);
		process.exitCode = 1;
		return;
	}
	if (process.exitCode === 1) {
		return;
	}
	const note = shrunk > 0 ? `; ${shrunk} shrank, run --update to record` : '';
	console.log(`i18n-lint: OK (${total} findings in ${counts.size} files; goal 0${note})`);
}

main();
