/* thirdPartyLicenses.ts -- GENERATED by scripts/gen-licenses.js; do not edit.
 *
 * Regenerate with `npm run build && npm run gen:licenses`.
 * tests/thirdPartyLicenses.spec.ts fails when this file and the tree
 * disagree, which is what a dependency bump trips.
 *
 * Every package with code in the built bundle, read from the build's own
 * source maps rather than from package.json: an optional dependency the
 * bundler dropped is not shipped, and a transitive one it kept is. The About
 * modal's libraries section is this list.
 *
 * The texts live next door in thirdPartyLicenseTexts.ts, imported on demand,
 * so this module stays small enough to sit in the main chunk.
 *
 * 37 packages. */

export interface ThirdPartyLicense {
	/** npm package name; the id a licence text is addressed by. */
	id: string;
	/** The name the credit line shows, which is not always the npm one. */
	name: string;
	version: string;
	/** The package's own `license` field, verbatim: usually SPDX, sometimes
	 *  a compound expression, occasionally neither. */
	spdx: string;
	url: string;
	/** The licence file names read, or the upstream source for a package
	 *  that ships none of its own. */
	files: string[];
}

export const THIRD_PARTY_LICENSES: ThirdPartyLicense[] = [
	{
		id: '@babel/runtime',
		name: '@babel/runtime',
		version: '7.29.7',
		spdx: 'MIT',
		url: 'https://babeljs.io/',
		files: ['LICENSE'],
	},
	{
		id: '@capacitor/app',
		name: '@capacitor/app',
		version: '8.1.1',
		spdx: 'MIT',
		url: 'https://capacitorjs.com/',
		files: ['LICENSE'],
	},
	{
		id: '@capacitor/core',
		name: '@capacitor/core',
		version: '8.5.0',
		spdx: 'MIT',
		url: 'https://capacitorjs.com/',
		files: ['LICENSE'],
	},
	{
		id: '@capacitor/filesystem',
		name: '@capacitor/filesystem',
		version: '8.1.2',
		spdx: 'MIT',
		url: 'https://capacitorjs.com/',
		files: ['LICENSE'],
	},
	{
		id: '@capacitor/share',
		name: '@capacitor/share',
		version: '8.0.1',
		spdx: 'MIT',
		url: 'https://capacitorjs.com/',
		files: ['LICENSE'],
	},
	{
		id: '@capacitor/synapse',
		name: '@capacitor/synapse',
		version: '1.0.4',
		spdx: 'ISC',
		url: 'https://github.com/ionic-team/capacitor-synapse',
		files: ['LICENSE.md'],
	},
	{
		id: 'canvg',
		name: 'canvg',
		version: '3.0.11',
		spdx: 'MIT',
		url: 'https://github.com/canvg/canvg',
		files: ['LICENSE'],
	},
	{
		id: 'clsx',
		name: 'clsx',
		version: '2.1.1',
		spdx: 'MIT',
		url: 'https://github.com/lukeed/clsx',
		files: ['license'],
	},
	{
		id: 'core-js',
		name: 'core-js',
		version: '3.49.0',
		spdx: 'MIT',
		url: 'https://github.com/zloirock/core-js',
		files: ['LICENSE'],
	},
	{
		id: 'dompurify',
		name: 'DOMPurify',
		version: '3.4.13',
		spdx: '(MPL-2.0 OR Apache-2.0)',
		url: 'https://github.com/cure53/DOMPurify',
		files: ['LICENSE', 'LICENSE-MPL'],
	},
	{
		id: 'fast-png',
		name: 'fast-png',
		version: '6.4.0',
		spdx: 'MIT',
		url: 'https://github.com/image-js/fast-png',
		files: ['LICENSE'],
	},
	{
		id: 'fflate',
		name: 'fflate',
		version: '0.8.3',
		spdx: 'MIT',
		url: 'https://github.com/101arrowz/fflate',
		files: ['LICENSE'],
	},
	{
		id: 'html2canvas',
		name: 'html2canvas',
		version: '1.4.1',
		spdx: 'MIT',
		url: 'https://github.com/niklasvh/html2canvas',
		files: ['LICENSE'],
	},
	{
		id: 'html2canvas-pro',
		name: 'html2canvas-pro',
		version: '2.3.3',
		spdx: 'MIT',
		url: 'https://github.com/yorickshan/html2canvas-pro',
		files: ['LICENSE'],
	},
	{
		id: 'idb',
		name: 'idb',
		version: '7.1.1',
		spdx: 'ISC',
		url: 'https://www.npmjs.com/package/idb',
		files: ['LICENSE'],
	},
	{
		id: 'iobuffer',
		name: 'IOBuffer',
		version: '5.4.0',
		spdx: 'MIT',
		url: 'https://github.com/image-js/iobuffer',
		files: ['LICENSE'],
	},
	{
		id: 'jspdf',
		name: 'jsPDF',
		version: '4.2.1',
		spdx: 'MIT',
		url: 'https://github.com/parallax/jsPDF',
		files: ['LICENSE'],
	},
	{
		id: 'leaflet',
		name: 'Leaflet',
		version: '1.9.4',
		spdx: 'BSD-2-Clause',
		url: 'https://leafletjs.com/',
		files: ['LICENSE'],
	},
	{
		id: 'pako',
		name: 'pako',
		version: '2.1.0',
		spdx: '(MIT AND Zlib)',
		url: 'https://github.com/nodeca/pako',
		files: ['LICENSE'],
	},
	{
		id: 'pdfjs-dist',
		name: 'pdf.js',
		version: '6.2.108',
		spdx: 'Apache-2.0',
		url: 'https://mozilla.github.io/pdf.js/',
		files: ['LICENSE'],
	},
	{
		id: 'performance-now',
		name: 'performance-now',
		version: '2.1.0',
		spdx: 'MIT',
		url: 'https://github.com/braveg1rl/performance-now',
		files: ['license.txt'],
	},
	{
		id: 'pmtiles',
		name: 'PMTiles',
		version: '4.4.1',
		spdx: 'BSD-3-Clause',
		url: 'https://github.com/protomaps/PMTiles',
		files: ['https://raw.githubusercontent.com/protomaps/PMTiles/main/LICENSE (read 2026-08-15)'],
	},
	{
		id: 'quickselect',
		name: 'quickselect',
		version: '3.0.0',
		spdx: 'ISC',
		url: 'https://github.com/mourner/quickselect',
		files: ['LICENSE'],
	},
	{
		id: 'raf',
		name: 'raf',
		version: '3.4.1',
		spdx: 'MIT',
		url: 'https://github.com/chrisdickinson/raf',
		files: ['LICENSE'],
	},
	{
		id: 'rbush',
		name: 'RBush',
		version: '4.0.1',
		spdx: 'MIT',
		url: 'https://github.com/mourner/rbush',
		files: ['LICENSE'],
	},
	{
		id: 'rgbcolor',
		name: 'rgbcolor',
		version: '1.0.1',
		spdx: 'MIT OR SEE LICENSE IN FEEL-FREE.md',
		url: 'https://github.com/stoyan/rgbcolor',
		files: ['LICENSE.md'],
	},
	{
		id: 'stackblur-canvas',
		name: 'StackBlur',
		version: '2.7.0',
		spdx: 'MIT',
		url: 'https://github.com/flozz/StackBlur',
		files: ['LICENSE-MIT.txt'],
	},
	{
		id: 'svelte',
		name: 'Svelte',
		version: '5.56.8',
		spdx: 'MIT',
		url: 'https://svelte.dev/',
		files: ['LICENSE.md'],
	},
	{
		id: 'svg-pathdata',
		name: 'svg-pathdata',
		version: '6.0.3',
		spdx: 'MIT',
		url: 'https://github.com/nfroidure/svg-pathdata',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-cacheable-response',
		name: 'workbox-cacheable-response',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-core',
		name: 'workbox-core',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-expiration',
		name: 'workbox-expiration',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-precaching',
		name: 'workbox-precaching',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-routing',
		name: 'workbox-routing',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-strategies',
		name: 'workbox-strategies',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'workbox-window',
		name: 'workbox-window',
		version: '7.4.1',
		spdx: 'MIT',
		url: 'https://developer.chrome.com/docs/workbox',
		files: ['LICENSE'],
	},
	{
		id: 'yaml',
		name: 'yaml',
		version: '2.9.0',
		spdx: 'ISC',
		url: 'https://eemeli.org/yaml/',
		files: ['LICENSE'],
	},
];

/** The entry a licence view was opened for, or undefined for an id that is
 *  no longer a dependency. */
export function thirdPartyLicense(id: string): ThirdPartyLicense | undefined {
	return THIRD_PARTY_LICENSES.find((e) => e.id === id);
}
