/* The seed tables of the two Restore default settings specs
 * (tests/restoreDefaults.spec.ts, tests/restoreViewerDefaults.spec.ts): a
 * valid non-default value for every key the registry classes as a
 * preference or a layout, and one key of every other class. */

/** A valid non-default value for every preference and layout key. */
export const PREF_SEEDS: Record<string, string> = {
	'loxodrome:layers': JSON.stringify({
		v: 1,
		baseLayer: 'ign',
		airspace: { controlled: true },
		chartStack: ['fr500'],
	}),
	'loxodrome:altitude-band': 'off:1500,6500',
	'loxodrome:notam-horizon': '24',
	'loxodrome:notam-rules': 'all',
	'loxodrome:notam-kind': 'area',
	'loxodrome:notams-on-route': 'on',
	'loxodrome:airspaces-on-route': 'on',
	'loxodrome:min-alt-danger': 'on',
	'loxodrome:notam-type-icons': 'off',
	'loxodrome:notam-qline-radius': 'off',
	'loxodrome:notam-qline-markers': 'off',
	'loxodrome:hide-airport-notam-markers': 'off',
	'loxodrome:affected-airspaces': 'off',
	'loxodrome:show-in-airspaces': 'on',
	'loxodrome:cursor-coords': 'off',
	'loxodrome:live-weather': 'off',
	'loxodrome:profile-all-airspaces': 'off',
	'loxodrome:gps-alt-datum': 'msl',
	'loxodrome:supaip-lang': 'fr',
	'loxodrome:sofia-lang': 'en',
	'loxodrome:aip-remark-lang': 'fr',
	'loxodrome:trace-export-format': 'igc',
	'loxodrome:trace-convert-imported': '1',
	'loxodrome:layers-control': 'map',
	'loxodrome:toolbar-in-flight': 'folded',
	'loxodrome:flight-fullscreen': 'off',
	'loxodrome:route-lock-in-flight': 'off',
	'loxodrome:theme': 'night',
	'loxodrome:night-dim': '50',
	'loxodrome:locale': 'fr',
	'loxodrome:notam-source': 'autorouter',
	'loxodrome:sofia-zone': 'EUR',
	'loxodrome:perf-nomogram-metric': 'groundRoll',
	'loxodrome:wind-model': 'icon_seamless',
	'loxodrome:wind-level': '5000',
	'loxodrome:wind-map': 'on',
	'loxodrome:wind-isotherm': 'on',
	'loxodrome:wind-isotherm-c': '-10',
	'loxodrome:wind-isobars': 'on',
	'loxodrome:radar-map': 'on',
	'loxodrome:radar-opacity': '50',
	'loxodrome:radar-coverage': 'off',
	'loxodrome:radar-loop': '120',
	'loxodrome:radar-product': 'RATE',
	'loxodrome:radar-strip': 'folded',
	'loxodrome:metar-map': 'on',
	'loxodrome:sigmet-map': 'on',
	'loxodrome:nav-alerts-off': '1',
	'loxodrome:nav-alert-avoid-off': '1',
	'loxodrome:nav-alert-clearance-off': '1',
	'loxodrome:nav-alert-equipment-off': '1',
	'loxodrome:nav-alert-caution-off': '1',
	'loxodrome:nav-alert-buffer': '500',
	'loxodrome:nav-alert-lookahead': '10',
	'loxodrome:nav-alert-audio': '1',
	'loxodrome:nav-alert-audio-caution': '1',
	'loxodrome:nav-alert-terrain-off': '1',
	'loxodrome:nav-alert-obstacle-off': '1',
	'loxodrome:nav-auto-stop': 'off',
	'loxodrome:nav-strip-collapsed': 'on',
	'loxodrome:nav-strip-hidden': 'on',
	'loxodrome:nav-overflight': 'off',
	'loxodrome:nav-strip-alt': 'agl',
	'loxodrome:nav-show-trace': 'off',
	'loxodrome:nav-vector': 'off',
	'loxodrome:nav-contact-map': 'off',
	'loxodrome:nav-playback-speed': '8',
	'loxodrome:nav-icon': 'glider',
	'loxodrome:profile-wind-barbs': 'off',
	'loxodrome:profile-freezing': 'off',
	'loxodrome:profile-clouds': 'off',
	'loxodrome:profile-obstacles': 'off',
	'loxodrome:profile-msa': 'off',
	'loxodrome:profile-notams': 'off',
	'loxodrome:profile-terrain-tint': 'off',
	'loxodrome:profile-class-a': 'off',
	'loxodrome:profile-class-b': 'off',
	'loxodrome:profile-class-c': 'off',
	'loxodrome:profile-class-d': 'off',
	'loxodrome:profile-class-e': 'off',
	'loxodrome:profile-zone-restricted': 'off',
	'loxodrome:profile-zone-military': 'off',
	'loxodrome:profile-zone-trafficmgmt': 'off',
	'loxodrome:profile-zone-other': 'off',
	'loxodrome:profile-activity': 'on',
	'loxodrome:profile-fir': 'off',
	'loxodrome:profile-siv': 'on',
	'loxodrome:sidebar-width': '520',
	'loxodrome:detail-width': '600',
	// The surface family: a placement away from its default and a dock size.
	'loxodrome:surface:navlog:placement': 'dock-bottom',
	'loxodrome:surface:routeProfile:size-bottom': '333',
	'loxodrome:surface:flightPrep:placement': 'full',
	// The one the NOTAM Viewer shares (its About has a single placement).
	'loxodrome:surface:airspaceProfile:placement': 'page',
	'loxodrome:surface:airspaceProfile:size-bottom': '280',
	'loxodrome:surface:airspaceProfile:size-right': '520',
};

const NOW = Date.now();

/** One of every other class, which the restore must leave byte for byte
 *  (the legacy one and the trace doc's symbol are the boot's to erase). */
export const KEEP_SEEDS: Record<string, string> = {
	'loxodrome:routes': '{"v":1,"activeIndex":0,"yaml":"version: 1"}',
	'loxodrome:routes-rescued': 'version: 1',
	// As an older build left it, still carrying the aircraft symbol: the
	// boot must drop that copy, or it would adopt it back over the plane the
	// restore puts back.
	'loxodrome:nav-trace': JSON.stringify({
		v: 1,
		iconKind: 'helicopter',
		recording: false,
		points: [],
	}),
	'loxodrome:nav-trace-parked': JSON.stringify({
		v: 1,
		recording: false,
		points: [{ lat: 48.6, lon: 2.4, timeMs: NOW - 3_600_000, altFt: 1500, speedKt: 90 }],
	}),
	'loxodrome:aircraft-user': '{"v":1,"planes":{}}',
	'loxodrome:aircraft-fuel': '{"v":1,"types":{}}',
	'loxodrome:flight-prep': '{"v":1}',
	'loxodrome:pilot': '{"v":1}',
	'loxodrome:sync': '{"v":1,"deviceId":"d","lastSeq":0,"docs":{},"tombstones":{}}',
	'loxodrome:account': '{"v":1}',
	'loxodrome:last-account': 'hash',
	'loxodrome:last-mode': 'personal',
	'loxodrome:shared-session': '1',
	'loxodrome:shared-marker': '1',
	'loxodrome:autorouter-proxy': 'https://proxy.example',
	'loxodrome:account-api': 'https://api.example',
	'loxodrome:radar-caution': 'seen',
	'loxodrome:nav-location-disclosed': '1',
	'loxodrome:nav-battery-asked': 'done',
	'loxodrome:fleet-expanded': '{"v":1,"groups":["Aeroclub"]}',
	'loxodrome:aircraft-selected': 'F-GORQ',
	'loxodrome:auto-night': '1',
	'loxodrome:aip-content-lang': 'en',
};
